repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    - id: mypy
      stages: [pre-merge-commit, pre-push, manual]
      exclude: ^tests/
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      # Run the Ruff formatter
      - id: ruff-format
      # Run the Ruff linter
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          # Rules E & F applied by default
          # https://github.com/charliermarsh/ruff/blob/main/README.md#supported-rules
          - --extend-select=A,B,I,N,W