name: CI

on:
  - pull_request
  - workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        cache: 'pip'
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --hook-stage manual --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        # https://github.com/actions/setup-python/issues/369
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install poetry
      run: pip install poetry 

    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

    - name: Install dependencies
    # https://github.com/nektos/act/issues/1639
      run: poetry install --no-ansi

    - name: Test
      run: poetry run pytest -v

